<?php include "include/header.php"; ?>

<div class="conatiner-fluid mt-5">
    <div class="card border-0">
        <div class="card-body px-5">
        <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laborum facere, quae natus suscipit nemo possimus error illum? Dolore numquam ex, repellendus accusantium possimus totam explicabo deleniti sequi, quibusdam vero dignissimos iste doloribus incidunt quia rerum in aliquam ducimus ratione porro quis animi repellat rem harum? Non aperiam, corrupti, amet odit quod officiis sed maxime, iste quam est cumque. Expedita veniam quasi explicabo saepe temporibus autem ducimus, placeat fugit dolorum fuga laboriosam illo quisquam iste excepturi doloribus aspernatur adipisci minima eius? Officiis earum minus nulla voluptas id voluptates quis explicabo doloremque.</p>
            <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquid unde facere, repellat esse similique quod maiores reprehenderit, perferendis dignissimos necessitatibus sed assumenda distinctio harum nobis nisi, suscipit ipsa. Repellat suscipit illo accusantium, quos exercitationem molestias possimus non optio error nemo assumenda ipsam modi neque enim. Ad impedit corrupti excepturi? Libero!</p>
            <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, rerum! Soluta, eum nesciunt nostrum dolorem, animi mollitia exercitationem aspernatur aliquam a dicta, ad amet.</p>
            <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laborum facere, quae natus suscipit nemo possimus error illum? Dolore numquam ex, repellendus accusantium possimus totam explicabo deleniti sequi, quibusdam vero dignissimos iste doloribus incidunt quia rerum in aliquam ducimus ratione porro quis animi repellat rem harum? Non aperiam, corrupti, amet odit quod officiis sed maxime, iste quam est cumque. Expedita veniam quasi explicabo saepe temporibus autem ducimus, placeat fugit dolorum fuga laboriosam illo quisquam iste excepturi doloribus aspernatur adipisci minima eius? Officiis earum minus nulla voluptas id voluptates quis explicabo doloremque.</p>
            <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, rerum! Soluta, eum nesciunt nostrum dolorem, animi mollitia exercitationem aspernatur aliquam a dicta, ad amet.</p>
            <p class="lead">Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus excepturi quis natus, tempora non possimus nostrum similique laboriosam aspernatur dignissimos a. Earum aliquid commodi placeat ipsa illum, facere, error fuga nihil beatae quo ex rerum ad deserunt fugiat. Obcaecati, nihil dicta! Autem, deserunt commodi rerum impedit, itaque a dolorum et eos reprehenderit accusantium voluptas obcaecati iusto excepturi at illum tenetur dolor temporibus earum incidunt explicabo voluptatum maxime omnis. Minima reprehenderit adipisci vitae repellat possimus voluptatum nam. Velit voluptas molestiae nulla, repellendus amet omnis quo modi tempore voluptatibus natus odit sequi, sit, est dolore unde! Id nam in nemo odio porro facilis perferendis architecto assumenda ullam dolores repudiandae facere, quasi esse laboriosam optio voluptate inventore. Voluptate ea vero non labore eius vel quod assumenda dolores voluptatum magnam exercitationem aspernatur esse nam ipsum, quibusdam ex nostrum atque temporibus ducimus dolor expedita distinctio fugiat sunt nulla! Culpa voluptatem debitis omnis reiciendis eos. Eligendi.</p>
        </div>
    </div>
</div>